### PR TITLE
Fix transitions for certain cases

### PR DESCRIPTION
**Pull request by mikumi**
Hello, great stuff, thank you! 

I had a couple of crashes and weird transitions though that I have fixed for me. I hope those will be helpful for you and others.
- I had crashes or black screens when transitioning between same-styled view controllers
- The top part of my view disappeared under the navigation bar after transitioning back to a solid view controller

### CODE REVIEW

**Comment by kafejo** [comment]
Ok, thanks. Send the update and I think it is ready for merge. I will extend the example for these use cases.

**Comment by kafejo** [comment]
Another thing is that you shouldn't use constants. Please use CGRectGetHeight(navigationBar.frame) + CGRectGetHeight(UIApplication.sharedApplication().statusBarFrame) instead. Thanks

**Comment by mikumi** [comment]
You are right. Actually I just copied most of that code from TFForwardAnimator.swift, reversing the effect of `let shiftedFrame = navigationControllerFrame.additiveRect(-64, direction: .Top)`

I noticed there is even another issue. returning `nil` from the `forwardAnimator`/`backwardAnimator` methods in `TFNavigationController` (which I just copied from another condition) disables manually swiping "back" to the previous controller. It only recognizes the start of the gesture and slides back automatically. Not sure if you have noticed this before. I haven't really looked so much at your code yet, so not sure if this is an easy fix or not.

**Comment by kafejo** [comment]
Ok, please provide the fix that I can merge it. I'll fix the rest then.

**Pull request closed without merging**
